"""
Measured confidence for recommendations.

Every recommendation carries a `confidence_source` naming the rule or AI
priority tier that produced it. `confidence_fields()` returns the hit rate the
offline benchmark (`backend/evals/calibration/`) measured for that source, or
the source's hand-set default when no measurement with enough samples exists.
Measurements live in `calibration_table.json` next to this module and are
regenerated by `python -m evals.calibration.run_eval --write-table`; nothing
here is learned at runtime.
"""

from __future__ import annotations

import json
from functools import lru_cache
from pathlib import Path
from typing import Any

from app.core.logging import get_logger

logger = get_logger(__name__)

CALIBRATION_TABLE_PATH = Path(__file__).with_name("calibration_table.json")

# Below this many scored recommendations a measured rate is too noisy to
# replace the hand-set default.
MIN_SAMPLES = 10

AI_HIGH = "ai:high"
AI_MEDIUM = "ai:medium"
AI_LOW = "ai:low"
RULE_DATA_QUALITY = "rule:data_quality"
RULE_FORECAST = "rule:forecast"
RULE_ANOMALY = "rule:anomaly"
# "Track X regularly" makes no falsifiable claim, so it is never scored or
# calibrated; it keeps its default.
RULE_TRACKING = "rule:tracking"

AI_SOURCE_BY_PRIORITY = {"High": AI_HIGH, "Medium": AI_MEDIUM, "Low": AI_LOW}

# The hand-set values in use before any measurement existed. Forecast
# recommendations have no fixed default: they inherit the forecast's own
# formula-based confidence (`forecasting._confidence`).
DEFAULT_CONFIDENCE = {
    AI_HIGH: 0.85,
    AI_MEDIUM: 0.7,
    AI_LOW: 0.55,
    RULE_DATA_QUALITY: 0.9,
    RULE_ANOMALY: 0.78,
    RULE_TRACKING: 0.72,
}


@lru_cache(maxsize=1)
def load_calibration_table() -> dict[str, dict[str, Any]]:
    """Return `{source: entry}` from the committed table, or `{}` if absent/invalid."""
    try:
        payload = json.loads(CALIBRATION_TABLE_PATH.read_text(encoding="utf-8"))
    except FileNotFoundError:
        return {}
    except (OSError, ValueError) as exc:
        logger.warning("Calibration table unreadable; using defaults", exc=str(exc))
        return {}
    sources = payload.get("sources") if isinstance(payload, dict) else None
    return sources if isinstance(sources, dict) else {}


def measured_confidence(source: str) -> float | None:
    """The benchmark-measured confidence for `source`, or None if not measured well enough."""
    entry = load_calibration_table().get(source)
    if not isinstance(entry, dict):
        return None
    try:
        samples = int(entry.get("n", 0))
        confidence = float(entry["confidence"])
    except (KeyError, TypeError, ValueError):
        return None
    if samples < MIN_SAMPLES or not 0.0 <= confidence <= 1.0:
        return None
    return confidence


def confidence_fields(source: str, default: float | None = None) -> dict[str, Any]:
    """The confidence keys every recommendation carries.

    `default` overrides the source's hand-set value (used by forecast
    recommendations, whose default is per-forecast).
    """
    measured = measured_confidence(source)
    fallback = DEFAULT_CONFIDENCE.get(source, 0.7) if default is None else default
    return {
        "confidence": measured if measured is not None else fallback,
        "confidence_source": source,
        "confidence_method": "measured" if measured is not None else "default",
    }
